apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  EULA: "TRUE"
  VERSION: "1.21.4"
  MOTD: "Minsu Kim | 934445327"
  MEMORY: "3G"
  TYPE: "VANILLA"
  SKIP_SERVER_PROPERTIES: "false"
